[package]
name = "stuff"
version = "0.1.0"
authors = ["WalrusWalrus <walruscodes@users.noreply.github.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
env_logger = "0.8.2"
log = "0.4"
serde = "1"
